services:
  mysql:
    image: mysql:8.0.36
    container_name: order-mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql

volumes:
    mysql-data: