services:
  mysql:
    image: mysql:8.0.36
    container_name: inventory-mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwertyuiop
    ports:
      - "3307:3306"
    volumes:
      - mysql-data2:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
    mysql-data2: